export default [
  {
    category: "Music",
    id: "622a1c397cc59eab6f950d2b",
    correctAnswer: "The Beatles",
    incorrectAnswers: ["Deep Purple", "Feeder", "Uriah Heep"],
    question:
      "Which English rock band released the song 'I Want to Hold Your Hand'?",
    tags: ["music"],
    type: "Multiple Choice",
    difficulty: "easy",
    regions: [],
  },
  {
    category: "Music",
    id: "622a1c357cc59eab6f94ff51",
    correctAnswer: "Michael Jackson",
    incorrectAnswers: ["Nicki Minaj", "Neil Young", "Eric Clapton"],
    question:
      "Which American singer released the song 'Wanna Be Startin' Somethin''?",
    tags: ["songs", "music"],
    type: "Multiple Choice",
    difficulty: "easy",
    regions: [],
  },
  {
    category: "Society & Culture",
    id: "6266e610ff2394bd44dee02e",
    correctAnswer: "One",
    incorrectAnswers: ["Yellow", "Eight", "Ten"],
    question: "In Spanish, what is the meaning of the word 'uno'?",
    tags: ["language", "translations", "society_and_culture"],
    type: "Multiple Choice",
    difficulty: "easy",
    regions: [],
  },
  {
    category: "Music",
    id: "625063b1e12f6dec240bdf7b",
    correctAnswer: "Ice Ice Baby",
    incorrectAnswers: [
      "I Want Candy",
      "Baby Got Back",
      "We're Not Gonna Take It",
    ],
    question: "Vanilla Ice had a one hit wonder in 1990 with which song?",
    tags: ["songs", "one_hit_wonders", "1990's", "general_knowledge", "music"],
    type: "Multiple Choice",
    difficulty: "easy",
    regions: [],
  },
  {
    category: "Music",
    id: "622a1c397cc59eab6f950d56",
    correctAnswer: "Marilyn Manson",
    incorrectAnswers: ["MercyMe", "Three 6 Mafia", "The Velvet Underground"],
    question: "Which band includes 'Marilyn Manson'?",
    tags: ["music"],
    type: "Multiple Choice",
    difficulty: "easy",
    regions: [],
  },
  {
    category: "Science",
    id: "6243334fcfaae40c129613d3",
    correctAnswer: "A Caterpillar",
    incorrectAnswers: ["A Codling", "A Chick", "A Spiderling"],
    question: "A young butterfly is known as what?",
    tags: ["science"],
    type: "Multiple Choice",
    difficulty: "easy",
    regions: [],
  },
  {
    category: "Sport & Leisure",
    id: "622a1c367cc59eab6f950026",
    correctAnswer: "Baseball",
    incorrectAnswers: ["Basketball", "American Football", "Soccer"],
    question: "With which sport is Babe Ruth associated?",
    tags: ["sport", "people", "general_knowledge"],
    type: "Multiple Choice",
    difficulty: "easy",
    regions: [],
  },
  {
    category: "Film & TV",
    id: "622a1c347cc59eab6f94fc0f",
    correctAnswer: '"Take your stinking paws off me, you damned dirty ape."',
    incorrectAnswers: [
      "\"Mrs. Robinson, you're trying to seduce me. Aren't you?\"",
      '"Toga! Toga!"',
      '"Attica! Attica!"',
    ],
    question: "Which of these quotes is from the film 'Planet of the Apes'?",
    tags: ["quotes", "film", "general_knowledge", "film_and_tv"],
    type: "Multiple Choice",
    difficulty: "easy",
    regions: [],
  },
  {
    category: "Society & Culture",
    id: "6293ebd57f41d6338b96eec3",
    correctAnswer: "Greek philosopher",
    incorrectAnswers: [
      "Ottoman Emperor.",
      "Roman General.",
      "Spiritual teacher and central figure of Christianity.",
    ],
    question: "Which of the following describes Aristotle?",
    tags: ["people", "history", "society_and_culture", "general_knowledge"],
    type: "Multiple Choice",
    difficulty: "easy",
    regions: [],
  },
  {
    category: "Film & TV",
    id: "622a1c357cc59eab6f94fc52",
    correctAnswer: '"Bond. James Bond."',
    incorrectAnswers: [
      '"What we\'ve got here is failure to communicate."',
      "\"Sawyer, you're going out a youngster, but you've t to come back a star!\"",
      '"Well, I don’t want to survive. I want to live."',
    ],
    question: "Which of these quotes is from the film 'Dr. No'?",
    tags: ["quotes", "film", "general_knowledge", "film_and_tv"],
    type: "Multiple Choice",
    difficulty: "easy",
    regions: [],
  },
];
